[package]
name = "renamer"
version = "0.1.0"
authors = ["mzelensky <maxim.zelensky@soxes.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
floating-duration = "*"
chrono = "*"
console = "*"